OpenXiangShan/YunSuan

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorIntAdder.scala

* func(vrsub): add rsub's OpType to package.scala & corresponding logic to VectorIntAdder.scala
* func(adc): support vmadc.vv vmadc.vi vmadc.vx

func(VIPU):support vrsub & vmadc

---

src/main/scala/yunsuan/vector/VectorALU/Permutation.scala
src/main/scala/yunsuan/vector/VectorALU/Reduction.scala
src/main/scala/yunsuan/vector/VectorALU/VAluBundles.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorALU/VAluUtils.scala
src/main/scala/yunsuan/vector/VectorALU/VFixPoint64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIntAdder64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIntFixpAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala
src/main/scala/yunsuan/vector/VectorALU/VMaskSlice.scala

* func(VIAlu): add VIAlu v1 code

func(VIAlu): add VIAlu code

---

src/main/scala/yunsuan/vector/VectorALU/Permutation.scala
src/main/scala/yunsuan/vector/VectorALU/VAluBundles.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorALU/VAluUtils.scala
src/main/scala/yunsuan/vector/VectorALU/VFixPoint64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIFuParameters.scala
src/main/scala/yunsuan/vector/VectorALU/VIntAdder64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIntFixpAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala

* func(VIAlu):add VIAlu code v2

func(VIAlu):add VIAlu code v2

---

src/test/csrc/golden_model/gm_common.cpp

fix bug: fflags

---

src/main/scala/yunsuan/vector/VectorFloatDivider.scala
src/test/csrc/emu.cpp
src/test/csrc/golden_model/gm_common.cpp
src/test/scala/top/VectorSimTop.scala

test: add clock wave, add reset wave, after bad trap add 10 cycles wave，change golden output fflags alignment，fix has_issued
func(VFDiv): assign no use fflags 0

test: fix some bugs of float(divider) framework 

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorALU/VAluUtils.scala
src/main/scala/yunsuan/vector/VectorIntAdder.scala

* func(VipuType):add more VipuType & fix bug of lmul=8 vl=128

func(VipuType):add more VipuType & fix bug of lmul=8 vl=128

---

src/main/scala/yunsuan/vector/VPERM/VCompress.scala
src/main/scala/yunsuan/vector/VPERM/VPermTop.scala
src/main/scala/yunsuan/vector/VPERM/VPermUtil.scala
src/main/scala/yunsuan/vector/VPERM/VRGather.scala
src/main/scala/yunsuan/vector/VPERM/VSlide.scala
src/test/csrc/golden_model/vector_permutation.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/include/iotype.h
src/test/csrc/include/test_driver.h
src/test/csrc/include/vpu_constant.h
src/test/csrc/test_driver.cpp
src/test/scala/top/VectorSimTop.scala

func(VPERM): add vperm top module
test(VPERM): add golden model and test: vslideup

test(VPERM): add golden model and test: vslideup

---

src/main/scala/yunsuan/package.scala

* refactor(VipuType): extract VialuFixType from VipuType

refactor(VipuType): extract VialuFixType from VipuType

---

build.sbt
src/main/scala/yunsuan/vector/VectorALU/VIAluFWrapper.scala
src/test/csrc/golden_model/vector_integer_aluF.cpp
src/test/csrc/golden_model/vector_permutation.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/include/iotype.h
src/test/csrc/include/test_driver.h
src/test/csrc/include/vpu_constant.h
src/test/csrc/test_driver.cpp
src/test/scala/top/VectorSimTop.scala

1. VADD_VV VSUB_VV test pass
TODO:
1. add more test for VIntFixpAlu

func(VIntFixpAlu):add test for VIntFixpAlu

---

src/main/scala/yunsuan/vector/VPERM/VCompress.scala
src/main/scala/yunsuan/vector/VPERM/VPermTop.scala
src/main/scala/yunsuan/vector/VPERM/VRGather.scala
src/main/scala/yunsuan/vector/VPERM/VSlide.scala
src/test/csrc/golden_model/vector_permutation.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/include/iotype.h
src/test/csrc/include/vpu_constant.h
src/test/csrc/test_driver.cpp
src/test/scala/top/VectorSimTop.scala
src/test/scala/vector/VectorTest.scala

func(VPERM): fix tail process, optimize vcompress, change vslide module name, change to 2-stage
test(VPERM): add golden model and test: vslidedown

test(VPERM): add golden model and test: vslidedown

---

build.sbt
src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorALU/Reduction.scala
src/main/scala/yunsuan/vector/VectorALU/VAluBundles.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorALU/VAluUtils.scala
src/main/scala/yunsuan/vector/VectorALU/VFixPoint64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIAluFWrapper.scala
src/main/scala/yunsuan/vector/VectorALU/VIFuParameters.scala
src/main/scala/yunsuan/vector/VectorALU/VIntAdder64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIntFixpAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala
src/main/scala/yunsuan/vector/VectorPerm/VPermBundles.scala
src/main/scala/yunsuan/vector/VectorPerm/VPermDecode.scala
src/main/scala/yunsuan/vector/vectorIMAC/VIMac64b.scala

func(IALU): add IALU V3

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala

* func(VpermType): add vfslide1up & vfslide1down

func(VpermType): add vfslide1up & vfslide1down

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala

* fix(vmvsx): fix Decode of vmvsx

fix(vmvsx): fix Decode of vmvsx

---

src/main/scala/yunsuan/vector/VPERM/VSlide.scala
src/test/csrc/golden_model/vector_permutation.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/include/iotype.h
src/test/csrc/include/test_driver.h
src/test/csrc/test_driver.cpp

test(VPERM): add golden model and test: vslide1up, vrgather, vslide1down

test(VPERM): add golden model and test: vslide1up, vrgather, vslide1down

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala

* func(VpermType): add isVsilde in VpermType
* fix(Permutation): fix bugs of Permutation

func(VpermType): add isVsilde in VpermType & fix bugs of Permutation

---

src/main/scala/yunsuan/vector/VPERM/VCompress.scala
src/test/csrc/golden_model/vector_permutation.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/test_driver.cpp

test(VPERM): add golden model and test: vcompress
func(VPERM): fix vcompress output_mask_ones_sum

test(VPERM): add golden model and test: vcompress

---

src/main/scala/yunsuan/package.scala

1. fix(package): fix bug that dummy and vnclip_wv encoding conflicts
2. fix(VialuFixType): fix a bug that vnclip_wv should be sign

fix(VialuFixType): fix a bug of vnclip_wv decode

---

src/main/scala/yunsuan/vector/VectorALU/VAluBundles.scala
src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorALU/VAluUtils.scala
src/main/scala/yunsuan/vector/VectorALU/VIntAdder64b.scala
src/main/scala/yunsuan/vector/VectorALU/VIntFixpAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala
src/main/scala/yunsuan/vector/VectorALU/VMaskSlice.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala
src/main/scala/yunsuan/vector/vectorIMAC/VIMac64b_noBooth.scala

* fix(VMask): fix some bug about VMask
* func(IALU): add IALU V4

func(IALU): add IALU V4

---

src/main/scala/yunsuan/vector/VectorALU/VAluDecode.scala
src/main/scala/yunsuan/vector/VectorPerm/VPermDecode.scala
src/main/scala/yunsuan/vector/VectorPermFsm/PermFsm.scala
src/main/scala/yunsuan/vector/VectorPermFsm/VPermFsmBundles.scala
src/main/scala/yunsuan/vector/VectorPermFsm/VPermFsmDecode.scala
src/main/scala/yunsuan/vector/vectorIMAC/VIMac.scala
src/test/scala/vector/VectorALU/VAluTestUtils.scala
src/test/scala/vector/VectorALU/VIAluWrapper.scala
src/test/scala/vector/VectorALU/VIMac64bSpec.scala
src/test/scala/vector/VectorALU/VIMacSpec.scala
src/test/scala/vector/VectorALU/VIntFixpAluSpec.scala
src/test/scala/vector/VectorALU/VPermSpec.scala
src/test/scala/vector/VectorALU/VPermWrapper.scala

func(IALU): add IALU V5

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala

fix(VIntMisc64b): fix a bug in VIntMisc64b
fix(vrgather): fix a bug that the value of vrgather_vd depends on ma

vialu: fix some bug

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/vector/VectorALU/Reduction.scala
src/main/scala/yunsuan/vector/VectorALU/VIntAdder64b.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala
src/main/scala/yunsuan/vector/VectorALU/VMaskSlice.scala
src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala
src/main/scala/yunsuan/vector/VectorPermFsm/PermFsm.scala
src/test/scala/vector/VectorALU/VIntFixpAluSpec.scala

fix(vcompress): fix a bug about vcompress

fix(vcompress): fix a bug about vcompress

---

src/main/scala/yunsuan/package.scala

* func(VimacType): add VimacType

func(VimacType): add VimacType

---

src/main/scala/yunsuan/package.scala

* fix(VimacType): fix a bug about VimacType

fix(VimacType): fix a bug about VimacType

---

src/main/scala/yunsuan/package.scala

* func(vmv_s_x):support vmv_s_x in VialuFixType

func(vmv_s_x):support vmv_s_x in VialuFixType

---

src/main/scala/yunsuan/package.scala

func(vmvnr): add decode of vmvnr

func(vmvnr): add decode of vmvnr

---

src/main/scala/yunsuan/encoding/Opcode/VialuOpcode.scala
src/main/scala/yunsuan/encoding/Opcode/VipuOpcode.scala
src/main/scala/yunsuan/encoding/VecDstType.scala
src/main/scala/yunsuan/encoding/VecFp.scala
src/main/scala/yunsuan/encoding/VecInt.scala
src/main/scala/yunsuan/encoding/package.scala
src/main/scala/yunsuan/package.scala

Add opcode and srcType encoding

---

src/main/scala/yunsuan/vector/VectorPerm/Permutation.scala

* use vsew_reg instead of vsew
* simplify the code for tail generate

vperm: fix vsew ctrl signal for vcompress

---

src/main/scala/yunsuan/vector/VectorALU/Reduction.scala
src/main/scala/yunsuan/vector/VectorALU/VIAlu.scala
src/main/scala/yunsuan/vector/VectorALU/VMask.scala
src/test/scala/vector/VectorALU/VIntFixpAluSpec.scala

fix vpu timing by delaying one cycle for reduction and vmask

fix vipu timing by adding a delay

---

src/main/scala/yunsuan/vector/VectorFloatAdder.scala
src/test/scala/top/VectorSimTop.scala

1. fix vs2 and vs1 swapping positions when widen occurs on vs1
2. fix vfalu timing
3. fix vfalu test

vfalu：fix timing

---

src/main/scala/yunsuan/vector/VectorALU/VIntMisc64b.scala
src/main/scala/yunsuan/vector/VectorConvert/util/CLZ.scala

1. fix result location for vclz.v and vctz.v
2. CLZ: Concatenate the input and 1 as the new input in priorityEncode to solve the input is all 0

Zvbb: fix vclz.v vctz.v and CLZ

---

src/main/scala/yunsuan/package.scala
src/main/scala/yunsuan/scalar/Convert.scala
src/main/scala/yunsuan/scalar/FPU.scala
src/main/scala/yunsuan/scalar/IntToFP.scala
src/main/scala/yunsuan/scalar/RoundingUnit.scala
src/main/scala/yunsuan/scalar/utils.scala
src/main/scala/yunsuan/vector/VectorConvert/CVT64.scala
src/main/scala/yunsuan/vector/VectorConvert/VCVT.scala
src/test/csrc/golden_model/gm_common.cpp
src/test/csrc/golden_model/scalar_float_convert.cpp
src/test/csrc/include/gm_common.h
src/test/csrc/include/test_driver.h
src/test/csrc/include/vpu_constant.h
src/test/csrc/test_driver.cpp
src/test/scala/top/VectorSimTop.scala

FCVT:add conversion for FP16 and modified CVT64 module to parameterize it
*The scalar float conversion function can be parameterized and trimmed in the CVT64
*Add scalar IntToFP conversion for FP16

FCVT:add conversion for FP16 and modified CVT64 module to parameterize it

---

src/main/scala/yunsuan/vector/VectorFloatAdder.scala

fix(vfalu): fix bug of f16_1_fp_a when fold to 1/4

fix(vfalu): fix bug of f16_1_fp_a when fold to 1/4

---

src/main/scala/yunsuan/package.scala

Modify indent and empty lines in package.scala

style: style change in package.scala

---

src/main/scala/yunsuan/vector/VectorBrainFloatAdder.scala

add bf16 vectoradder in a new module

add bf16 vectoradder

---

src/main/scala/yunsuan/fpu/FloatFMA.scala

signficandwidth fp64 is 53
signficandwidth fp32 is 24
signficandwidth fp16 is 11
53-24 = 29
53-11 = 42

fix bug in floatfma
